### ISSUE TITLE
Can't install on Arduino Uno (clone board)

### ISSUE THREAD

**Issue by lalcaraz** [henols/firestarter_app#7]
As tittle says, Im getting problems getting Firestarted on the arduino board. Safe to say it doesn't work on a Leonardo board but I assume it's not meant to be compatible.

(firestarter) lalcaraz@macmini firestarter % firestarter -v fw --install --port /dev/cu.usbserial-A5069RR4
Reading firmware version
Config data:
{'state': 13, 'verbose': True}
Check port: /dev/cu.usbserial-A5069RR4
TIMEOUT_ERROR - Timeout (expecting response)
No programmer found
Trying to install firmware version: 1.2.3
Found programmer at port: /dev/cu.usbserial-A5069RR4
Downloading firmware...
Firmware downloaded
Installing firmware
Firmware updated
(firestarter) lalcaraz@macmini firestarter % firestarter -v hw
Reading hardware revision
Config data:
{'state': 15, 'verbose': True}
Check port: /dev/cu.usbserial-A5069RR4
TIMEOUT_ERROR - Timeout (expecting response)
No programmer found
(firestarter) lalcaraz@macmini firestarter % 
(firestarter) lalcaraz@macmini firestarter % firestarter -v fw --install                                  
Reading firmware version
Config data:
{'state': 13, 'verbose': True}
Check port: /dev/cu.usbserial-A5069RR4
TIMEOUT_ERROR - Timeout (expecting response)
No programmer found
Trying to install firmware version: 1.2.3
Found programmer at port: /dev/cu.usbserial-A5069RR4
Downloading firmware...
Firmware downloaded
Installing firmware
Firmware updated
(firestarter) lalcaraz@macmini firestarter % firestarter -v fw
Reading firmware version
Config data:
{'state': 13, 'verbose': True}
Check port: /dev/cu.usbserial-A5069RR4
TIMEOUT_ERROR - Timeout (expecting response)
No programmer found
(firestarter) lalcaraz@macmini firestarter % firestarter -v hw
Reading hardware revision
Config data:
{'state': 15, 'verbose': True}
Check port: /dev/cu.usbserial-A5069RR4
TIMEOUT_ERROR - Timeout (expecting response)
No programmer found
(firestarter) lalcaraz@macmini firestarter % 

What do you guys think of this?

Environment: Mac Mini M1
Board: Arduino Uno clone

**Comment by henols** [comment]
What is the firestarter version, try updating the python app.

**Comment by lalcaraz** [comment]
(firestarter) lalcaraz@macmini firestarter % firestarter --version
Firestarter version: 1.1.29
(firestarter) lalcaraz@macmini firestarter % date
Wed Nov 27 16:15:37 EST 2024
(firestarter) lalcaraz@macmini firestarter % 
(firestarter) lalcaraz@macmini firestarter % pip show firestarter
Name: firestarter
Version: 1.1.29
Summary: EPROM burner software for the Relatively Universal ROM Programmer
Home-page: 
Author: 
Author-email: Henrik Olsson <henols@gmail.com>
License: 
Location: /Users/lalcaraz/Development/firestarter/lib/python3.13/site-packages
Requires: argparse, pyserial, requests
Required-by: 
(firestarter) lalcaraz@macmini firestarter % 


I'm gonna nuke the venv and install from scratch

**Comment by lalcaraz** [comment]
Installed it globally on MacOS with pipx (available in homebrew) and works as expected.
Thanks!


lalcaraz@macmini ~ % firestarter fw --install 
Reading firmware version
Connected to programmer
Firmware version: 1.2.3
You have the latest version
lalcaraz@macmini ~ % firestarter hw           
Reading hardware revision
Connected to programmer
Hardware revision: Rev0
lalcaraz@macmini ~ % firestarter config 
Reading configuration
Connected to programmer
Config: R1: 270000, R2: 44000
lalcaraz@macmini ~ % firestarter --version
Firestarter version: 1.2.2
lalcaraz@macmini ~ % date
Wed Nov 27 16:32:30 EST 2024
lalcaraz@macmini ~ % 



Steps:
[ install brew.sh] 
brew install pipx
pipx install firestarter
pipx ensurepath
firestarter

**Comment by henols** [comment]
Awesome that you got it working
