### ISSUE TITLE
How to add a ROM type to the supported list?

### ISSUE THREAD

**Issue by lalcaraz** [henols/firestarter_app#9]
Howdy!

I would like to add support for some EPROMs that I need to read, like 2332, 2316, 2364, commonly known as Commodore Vic20 Character ROMs. Is there a way to contribute and add those chips? Is there a way to read them under a different type?

Thanks.

**Comment by lalcaraz** [comment]
On top of that, I'm getting different chip IDs every time I try to identify it

lalcaraz@macmini ~ % firestarter id 27HC256      
Checking Chip ID: 27HC256
Connected to programmer

Error: Chip ID 0x15a dont match expected ID 0x2994
lalcaraz@macmini ~ % firestarter id AM27C64
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x6965 dont match expected ID 0x115
lalcaraz@macmini ~ % firestarter id AM27C64
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x4101 dont match expected ID 0x115
lalcaraz@macmini ~ % 
lalcaraz@macmini ~ % 
lalcaraz@macmini ~ % firestarter id AM27C64
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x4101 dont match expected ID 0x115
lalcaraz@macmini ~ % firestarter id M27C256B    
Checking Chip ID: M27C256B
Connected to programmer

Error: Chip ID 0x8103 dont match expected ID 0x208d
lalcaraz@macmini ~ % firestarter id M27C256B
Checking Chip ID: M27C256B
Connected to programmer

Error: Chip ID 0x8103 dont match expected ID 0x208d
lalcaraz@macmini ~ % firestarter id AM27C64 
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x4101 dont match expected ID 0x115
lalcaraz@macmini ~ % firestarter id AM27C512
Checking Chip ID: AM27C512
Connected to programmer

Error: Chip ID 0x8103 dont match expected ID 0x191
lalcaraz@macmini ~ % firestarter id AM27C64 
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x6961 dont match expected ID 0x115
lalcaraz@macmini ~ % 

lalcaraz@macmini ~ % firestarter hw        
Reading hardware revision
Connected to programmer
Hardware revision: Rev2
lalcaraz@macmini ~ % firestarter id AM27C64
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x666e dont match expected ID 0x115
lalcaraz@macmini ~ % firestarter id AM27C64 
Checking Chip ID: AM27C64
Connected to programmer

Error: Chip ID 0x666e dont match expected ID 0x115
lalcaraz@macmini ~ % firestarter id M27C256B
Checking Chip ID: M27C256B
Connected to programmer

Error: Chip ID 0xebf9 dont match expected ID 0x208d
lalcaraz@macmini ~ % 

This is an S27c256 -20 FA

**Comment by lalcaraz** [comment]
Oh, yeah, my env

lalcaraz@macmini ~ % firestarter fw --install      
Reading firmware version
Connected to programmer
Firmware version: 1.2.3
You have the latest version

lalcaraz@macmini ~ % firestarter --version   
Firestarter version: 1.2.4
lalcaraz@macmini ~ %

**Comment by henols** [comment]
The old Commodore roms cant be supported by the hardware since RURP only
supports the JEDEC  layout, you need to build an adapter.

**Comment by henols** [comment]
Join Anders Nilsens Discord to get some help to build one and faster
answers to your questions.

**Comment by lalcaraz** [comment]
will do. Thanks :-)
